spring:
  profiles:
    active: local
    include:
    - oauth
    - awskey
  servlet:
    multipart:
      max-file-size: 20MB # 추후 변경
      max-request-size: 20MB # 추후 변경

JWT:
  TOKEN:
    KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

file:
  dir: /Users/seungjulee/study/demo/file/

#cloud:
#  aws:
#    accessKey: DUMMY
#    secretKey: DUMMY
#    s3:
#      bucket: whatz-s3

