spring:
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
