spring:
  datasource:
    url: jdbc:mysql://database-1.czabbv6qfzii.ap-northeast-2.rds.amazonaws.com:3306/whatz_db?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
